q1 results:
    q1 - 1 result:
        ❌ Test case failed
        Trying:
            square(3)
        Expecting:
            9
        **********************************************************************
        Line 2, in q1 0
        Failed example:
            square(3)
        Expected:
            9
        Got:
            243

    q1 - 2 result:
        ❌ Test case failed
        Trying:
            square(2.5)
        Expecting:
            6.25
        **********************************************************************
        Line 2, in q1 1
        Failed example:
            square(2.5)
        Expected:
            6.25
        Got:
            97.65625

    q1 - 3 result:
        ❌ Test case failed
        Trying:
            square(6)
        Expecting:
            36
        **********************************************************************
        Line 2, in q1 2
        Failed example:
            square(6)
        Expected:
            36
        Got:
            7776

    q1 - 4 result:
        ❌ Test case failed
        Trying:
            square(1.5)
        Expecting:
            2.25
        **********************************************************************
        Line 2, in q1 3
        Failed example:
            square(1.5)
        Expected:
            2.25
        Got:
            7.59375

q2b results: All test cases passed!

q2 results: All test cases passed!

q3 results:
    q3 - 1 result:
        ❌ Test case failed
        Trying:
            x
        Expecting:
            True
        **********************************************************************
        Line 2, in q3 0
        Failed example:
            x
        Exception raised:
            Traceback (most recent call last):
              File "/root/miniforge3/envs/otter-env/lib/python3.9/doctest.py", line 1334, in __run
                exec(compile(example.source, filename, "single",
              File "<doctest q3 0[0]>", line 1, in <module>
                x
            NameError: name 'x' is not defined

    q3 - 2 result:
        ❌ Test case failed
        Trying:
            if x:
                print("yep")
            else:
                print("nope")
        Expecting:
            yep
        **********************************************************************
        Line 2, in q3 1
        Failed example:
            if x:
                print("yep")
            else:
                print("nope")
        Exception raised:
            Traceback (most recent call last):
              File "/root/miniforge3/envs/otter-env/lib/python3.9/doctest.py", line 1334, in __run
                exec(compile(example.source, filename, "single",
              File "<doctest q3 1[0]>", line 1, in <module>
                if x:
            NameError: name 'x' is not defined

q4 results: All test cases passed!

q6 results:
    q6 - 1 result:
        ❌ Test case failed
        Trying:
            fib = fiberator()
        Expecting nothing
        ok
        Trying:
            next(fib) == 0 and next(fib) == 1
        Expecting:
            True
        **********************************************************************
        Line 3, in q6 0
        Failed example:
            next(fib) == 0 and next(fib) == 1
        Expected:
            True
        Got:
            False

    q6 - 2 result:
        ❌ Test case failed
        Trying:
            fib = fiberator()
        Expecting nothing
        ok
        Trying:
            for _ in range(10):
                print(next(fib))
        Expecting:
            0
            1
            1
            2
            3
            5
            8
            13
            21
            34
        **********************************************************************
        Line 3, in q6 1
        Failed example:
            for _ in range(10):
                print(next(fib))
        Exception raised:
            Traceback (most recent call last):
              File "/root/miniforge3/envs/otter-env/lib/python3.9/doctest.py", line 1334, in __run
                exec(compile(example.source, filename, "single",
              File "<doctest q6 1[1]>", line 2, in <module>
                print(next(fib))
            StopIteration

q7 results: All test cases passed!